Hw03 frequency analysis
Konata69/hw-test pull request #3
Opened 2023-04-28 12:44 UTC by Konata69

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-06-01 21:04 UTC, ityulkanov requested changes
Предлагаю вам немного подсократить и упростить решение, и приму.

2023-06-01 21:04 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +		}
```suggestion
            words[word]++
```

2023-06-01 21:04 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +	delete(words, "-")
это можно было бы удалить тем же регекспом

2023-06-01 21:04 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +	})
по сути промежуточный слайс нам и не нужен, т.к. мы можем точно так же сортировать наш интовый массив

2023-06-01 21:04 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +	}
эту строку соответственно тоже можно сократить, если наша сортировка будет происходить без промежуточного массива, тем самым просто подставляя в операции со слайсом `:sliceLength`

2023-06-02 08:43 UTC, Konata69 commented on hw03_frequency_analysis/top.go
> +		}
Исправил

2023-06-02 08:43 UTC, Konata69 commented on hw03_frequency_analysis/top.go
> +	delete(words, "-")
Поменял регексп, чтобы он не брал тире

2023-06-02 08:50 UTC, Konata69 commented on hw03_frequency_analysis/top.go
> +	})
О каком интовом массиве идет речь?

В решении я использую мапу map[string]int{}
Нужно её сортировать по двум полям (в случае одинаковых частот)
Мапу го сортировать не умеет
Поэтому переводим её в слайс объектов и сортируем как показано в коде

Покажите пример как можно обойтись без использования промежуточного слайса

2023-06-02 11:42 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +	})
Да, точно, Тут неправ. Без промежуточного слайса не обойтись. Извиняюсь.

2023-06-02 11:43 UTC, ityulkanov approved these changes

2023-06-21 12:24 UTC, merged