Hw07 file copying
Konata69/hw-test pull request #7
Opened 2023-06-22 12:49 UTC by Konata69

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-06-23 13:35 UTC, ityulkanov requested changes
Добавьте, пожалуйста ещё тест на проверку != fromPath и toPath

2023-06-23 13:35 UTC, ityulkanov commented on hw07_file_copying/main.go
> +
а зачем тут нам эта обёртка?

2023-06-23 13:35 UTC, ityulkanov commented on hw07_file_copying/copy.go
> +	bar.Finish()
наверное лучше было бы даже сразу после вызова pb.Start вызывать defer pb.Finish() чтобы в случае ошибки копирования все ресурсы открытые progress баром точно закрылись

2023-06-23 13:35 UTC, ityulkanov commented on hw07_file_copying/copy.go
> +	fileTo, err := os.Create(toPath)
необходимо ещё проверять что topath != fromPath, причём именно путь, а не string value

2023-06-27 08:52 UTC, Konata69 commented on hw07_file_copying/main.go
> +
Была актуальна до рефакторинга. Сейчас убрал

2023-06-27 08:53 UTC, Konata69 commented on hw07_file_copying/copy.go
> +	bar.Finish()
Поправил

2023-06-27 08:57 UTC, Konata69 commented on hw07_file_copying/copy.go
> +	fileTo, err := os.Create(toPath)
Что значит "именно путь, а не string value"?
Как еще можно сравнить пути двух файлов кроме как по их строкам?

2023-06-27 10:33 UTC, Konata69 commented on hw07_file_copying/copy.go
> +	fileTo, err := os.Create(toPath)
Добавил проверку путей файлов и юнит тест на это

2023-06-27 10:42 UTC, ityulkanov commented on hw07_file_copying/copy.go
> +	fileTo, err := os.Create(toPath)
Ну к примеру путь ~/Downloads/file1.txt и home/user/Downloads/file1.txt - это равнозначные пути по сути, но если их сравнивать как strings мы получим not equal.

2023-06-27 11:07 UTC, ityulkanov commented on hw07_file_copying/copy.go
> +	fileTo, err := os.Create(toPath)
Это важно знать, думаю. Но могу принять и как есть если уже лень что либо дальше делать, нет проблем)

2023-06-27 11:07 UTC, ityulkanov approved these changes

2023-06-27 11:27 UTC, merged